

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e5e8eb",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006e0c",
        "on-primary": "#ffffff",
        "inverse-primary": "#b0c8eb",
        "on-secondary-fixed-variant": "#005307",
        "tertiary-fixed-dim": "#b6c8de",
        "on-secondary-fixed": "#002201",
        "surface-dim": "#d7dadd",
        "secondary-container": "#49fd48",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#091d2d",
        "surface-bright": "#f7fafd",
        "on-surface-variant": "#43474d",
        "outline": "#74777e",
        "primary-fixed": "#d2e4ff",
        "primary-container": "#0a2540",
        "on-secondary-container": "#00710d",
        "on-primary-fixed-variant": "#314865",
        "secondary-fixed": "#75ff69",
        "on-tertiary-container": "#7b8da1",
        "on-error-container": "#93000a",
        "background": "#f7fafd",
        "on-surface": "#181c1e",
        "on-background": "#181c1e",
        "error": "#ba1a1a",
        "surface-container-low": "#f1f4f7",
        "tertiary": "#00101f",
        "inverse-on-surface": "#eef1f4",
        "on-tertiary-fixed-variant": "#37485a",
        "on-error": "#ffffff",
        "surface-tint": "#49607e",
        "on-primary-fixed": "#001c37",
        "surface-variant": "#e0e3e6",
        "secondary-fixed-dim": "#25e531",
        "outline-variant": "#c4c6ce",
        "on-primary-container": "#768dad",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#132636",
        "primary": "#000f22",
        "tertiary-fixed": "#d1e4fb",
        "error-container": "#ffdad6",
        "surface-container": "#ebeef1",
        "surface": "#f7fafd",
        "surface-container-highest": "#e0e3e6",
        "primary-fixed-dim": "#b0c8eb",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};